version: "3.7"

services:
    # image project
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        image: smartlead/talklead-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - smartlead

    # nginx
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - smartlead

    # db mysql
    mysql:
        container_name: mysql
        image: mysql:5.7.34
        platform: linux/amd64
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3390:3306"
        networks:
            - smartlead

    #PhpMyadmin
    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - UPLOAD_LIMIT= 100M
        networks:
            - smartlead

    cron:
        build:
            context: .
            dockerfile: cron.dockerfile
        container_name: cron
        volumes:
            - ./:/var/www
        networks:
            - smartlead

networks:
    smartlead:
        driver: bridge
